version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_hbtn
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hbtn_0e_0_usa
      MYSQL_USER: hbtn_user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

